name: Update dependencies

on:
  create:
    branches: [ master ]

jobs:
  update-dependencies:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm i -g npm-check-updates
    - run: ncu -u
    - run: git config user.name "enricoschaaf"
    - run: git add package.json
    - run: git commit -m "Update dependencies"
    - run: git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
    - run: git push
