name: Update dependencies

on:
  create:
    branches: [ master ]

jobs:
  update-dependencies:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm i -g npm-check-updates
    - run: ncu -u
