name: Update name

on:
  create:
    branches: [ master ]

jobs:
  update-name:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run:   echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
      shell: bash
    - uses: actions/setup-node@v1
    - run: git config user.name $GITHUB_ACTOR
    - run: git pull
    - run: npm i -g json
    - run: json -I -f package.json -e "this.name='$REPOSITORY_NAME'"
    - run: git add package.json
    - run: git commit -m "Update name"
    - run: git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
    - run: git push
